apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-crd
  namespace: fleet-default
spec:
  chart: "rancher-monitoring-crd"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring-crd"
  version: 107.2.0-rc.1+up69.8.2-rancher.15
  defaultNamespace: "cattle-monitoring-system"
