apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring
  namespace: fleet-default
spec:
  chart: "rancher-monitoring"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring"
  version: 107.2.0-rc.1+up69.8.2-rancher.15
  diff:
    comparePatches:
      - apiVersion: admissionregistration.k8s.io/v1beta1
        kind: MutatingWebhookConfiguration
        name: rancher-monitoring-admission
        jsonPointers:
          - /webhooks/0/failurePolicy
      - apiVersion: admissionregistration.k8s.io/v1beta1
        kind: ValidatingWebhookConfiguration
        name: rancher-monitoring-admission
        jsonPointers:
          - /webhooks/0/failurePolicy
  defaultNamespace: "cattle-monitoring-system"
